// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ2UTEpY8t6J7DM2HffqBhVYAVSEoocUs',
    appId: '1:1006666289894:web:fc6095478b4bb65642e127',
    messagingSenderId: '1006666289894',
    projectId: 'movie-mobile-application',
    authDomain: 'movie-mobile-application.firebaseapp.com',
    storageBucket: 'movie-mobile-application.firebasestorage.app',
    measurementId: 'G-BR2NQYTSH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf7k9hdoWTJG3loGJDm4xzdIBwzroLA2U',
    appId: '1:1006666289894:android:088efcfba4e5638842e127',
    messagingSenderId: '1006666289894',
    projectId: 'movie-mobile-application',
    storageBucket: 'movie-mobile-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6A0MapyjHgULEwIon5r6AKehxMPjHq_k',
    appId: '1:1006666289894:ios:abb9f834e9bb2eb842e127',
    messagingSenderId: '1006666289894',
    projectId: 'movie-mobile-application',
    storageBucket: 'movie-mobile-application.firebasestorage.app',
    iosBundleId: 'com.example.movie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6A0MapyjHgULEwIon5r6AKehxMPjHq_k',
    appId: '1:1006666289894:ios:abb9f834e9bb2eb842e127',
    messagingSenderId: '1006666289894',
    projectId: 'movie-mobile-application',
    storageBucket: 'movie-mobile-application.firebasestorage.app',
    iosBundleId: 'com.example.movie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ2UTEpY8t6J7DM2HffqBhVYAVSEoocUs',
    appId: '1:1006666289894:web:7e95cbc27863435642e127',
    messagingSenderId: '1006666289894',
    projectId: 'movie-mobile-application',
    authDomain: 'movie-mobile-application.firebaseapp.com',
    storageBucket: 'movie-mobile-application.firebasestorage.app',
    measurementId: 'G-PLR9JHL3RE',
  );
}
