// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCodH3Zr_1zI3X34ukAaX7p4BZqmrnuONk',
    appId: '1:301625127703:web:380c307d3e23162036bd52',
    messagingSenderId: '301625127703',
    projectId: 'movieapp-9da1e',
    authDomain: 'movieapp-9da1e.firebaseapp.com',
    storageBucket: 'movieapp-9da1e.firebasestorage.app',
    measurementId: 'G-QGL78H6JWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXojAn13tFl2Y7N16Jre4NcxF5xCurVNM',
    appId: '1:301625127703:android:382a7b8040f6e7d936bd52',
    messagingSenderId: '301625127703',
    projectId: 'movieapp-9da1e',
    storageBucket: 'movieapp-9da1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIRgdtIxvChrZLgR0nHFJWE0UGt6PM8Q0',
    appId: '1:301625127703:ios:135a51d93b9130c636bd52',
    messagingSenderId: '301625127703',
    projectId: 'movieapp-9da1e',
    storageBucket: 'movieapp-9da1e.firebasestorage.app',
    iosBundleId: 'com.example.movie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIRgdtIxvChrZLgR0nHFJWE0UGt6PM8Q0',
    appId: '1:301625127703:ios:135a51d93b9130c636bd52',
    messagingSenderId: '301625127703',
    projectId: 'movieapp-9da1e',
    storageBucket: 'movieapp-9da1e.firebasestorage.app',
    iosBundleId: 'com.example.movie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCodH3Zr_1zI3X34ukAaX7p4BZqmrnuONk',
    appId: '1:301625127703:web:69894f0f84a2b26436bd52',
    messagingSenderId: '301625127703',
    projectId: 'movieapp-9da1e',
    authDomain: 'movieapp-9da1e.firebaseapp.com',
    storageBucket: 'movieapp-9da1e.firebasestorage.app',
    measurementId: 'G-NR5BMFBRQ4',
  );
}
