// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9kTaDTk1mpdKNCkJIJEIGn_sBcOFE4_M',
    appId: '1:59812616431:web:08da15bee81e68e9c1e31a',
    messagingSenderId: '59812616431',
    projectId: 'movie-mobile-app-54cd2',
    authDomain: 'movie-mobile-app-54cd2.firebaseapp.com',
    storageBucket: 'movie-mobile-app-54cd2.firebasestorage.app',
    measurementId: 'G-HM8X6LRWKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiwqanTUyuxDmb3zrGnmAtfKGwiviwX90',
    appId: '1:59812616431:android:3069d2e4d695f2b6c1e31a',
    messagingSenderId: '59812616431',
    projectId: 'movie-mobile-app-54cd2',
    storageBucket: 'movie-mobile-app-54cd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5fBXs6cO1HXZtYWQ-15sYxX4i0RMJEl0',
    appId: '1:59812616431:ios:dc418700efc7bcbbc1e31a',
    messagingSenderId: '59812616431',
    projectId: 'movie-mobile-app-54cd2',
    storageBucket: 'movie-mobile-app-54cd2.firebasestorage.app',
    iosBundleId: 'com.example.movie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5fBXs6cO1HXZtYWQ-15sYxX4i0RMJEl0',
    appId: '1:59812616431:ios:dc418700efc7bcbbc1e31a',
    messagingSenderId: '59812616431',
    projectId: 'movie-mobile-app-54cd2',
    storageBucket: 'movie-mobile-app-54cd2.firebasestorage.app',
    iosBundleId: 'com.example.movie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9kTaDTk1mpdKNCkJIJEIGn_sBcOFE4_M',
    appId: '1:59812616431:web:87aca7b2343a4ac6c1e31a',
    messagingSenderId: '59812616431',
    projectId: 'movie-mobile-app-54cd2',
    authDomain: 'movie-mobile-app-54cd2.firebaseapp.com',
    storageBucket: 'movie-mobile-app-54cd2.firebasestorage.app',
    measurementId: 'G-FQDXFQ4338',
  );
}
